openapi: 3.0.0
info:
  title: openapi
  version: '1.0'
  description: Caff webshop API
servers:
  - url: 'http://localhost:8080/api'
paths:
  /auth/register:
    post:
      summary: ''
      operationId: post-auth-register
      description: registration api
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationRequest'
          application/xml:
            schema:
              type: object
              properties: {}
        description: ''
      tags:
        - auth
  /auth/login:
    post:
      summary: ''
      operationId: post-auth-login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '403':
          description: Forbidden
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
          application/xml:
            schema:
              type: object
              properties: {}
      tags:
        - auth
      description: Login API
components:
  schemas:
    RegistrationRequest:
      title: RegistrationRequest
      type: object
      properties:
        name:
          type: string
        username:
          type: string
        email:
          type: string
        password:
          type: string
        confirmPassword:
          type: string
      required:
        - name
        - username
        - email
        - password
        - confirmPassword
    LoginRequest:
      title: LoginRequest
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
    LoginResponse:
      title: LoginResponse
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
        userDetails:
          type: object
          required:
            - id
            - name
            - username
            - roles
          properties:
            id:
              type: integer
            name:
              type: string
            username:
              type: string
            roles:
              type: array
              items:
                type: string
      required:
        - accessToken
        - refreshToken
        - userDetails
tags:
  - name: auth
